### ISSUE TITLE
order from outside kuwait payment option issue

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-maintenance#1]
if customer order from outside kuwait, payment must be sent by the link to customer no online payment option.. (animok store will sent the payment link for both payment item and delivery charge together).. msg will sent like- **we will contact you for payment process**

https://github.com/ZateLabClients/animok-maintenance/assets/124394535/57f3e48f-8621-46dc-8699-e3417c53eefc

**Comment by ZateLabClients** [comment]
complete. Please verify from ur side too
